pypro02/base/urls.py
from django.urls import path
from . import views


app_name = 'base'
urlpatterns = [
    path('', views.home, name='home')
]

pypro02/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pypro02.base.urls')),
    path('aperitivos/', include('pypro02.aperitivos.urls')),
    path('modulos/', include('pypro02.modulos.urls')),
    path('turmas/', include('pypro02.turmas.urls')),
    path('contas/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path("__debug__/", include(debug_toolbar.urls))
    )

pypro02/base/models.py
from django.db import models
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.mail import send_mail
# from django.apps import apps
from django.contrib.auth.hashers import make_password
from django.contrib import auth


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Create and save a user with the given email, and password.
        """
        if not email:
            raise ValueError("The given username must be set")
        email = self.normalize_email(email)
        # Lookup the real model class from the global app registry so this
        # manager method can be used in migrations. This is fine because
        # managers are by definition working on the real model.
        # GlobalUserModel = apps.get_model(
        #     self.model._meta.app_label, self.model._meta.object_name
        # )
        user = self.model(email=email, **extra_fields)
        user.password = make_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, username, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", False)
        extra_fields.setdefault("is_superuser", False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email=None, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        if extra_fields.get("is_staff") is not True:
            raise ValueError("Superuser must have is_staff=True.")
        if extra_fields.get("is_superuser") is not True:
            raise ValueError("Superuser must have is_superuser=True.")

        return self._create_user(email, password, **extra_fields)

    def with_perm(
        self, perm, is_active=True, include_superusers=True, backend=None, obj=None
    ):
        if backend is None:
            backends = auth._get_backends(return_tuples=True)
            if len(backends) == 1:
                backend, _ = backends[0]
            else:
                raise ValueError(
                    "You have multiple authentication backends configured and "
                    "therefore must provide the `backend` argument."
                )
        elif not isinstance(backend, str):
            raise TypeError(
                "backend must be a dotted import path string (got %r)." % backend
            )
        else:
            backend = auth.load_backend(backend)
        if hasattr(backend, "with_perm"):
            return backend.with_perm(
                perm,
                is_active=is_active,
                include_superusers=include_superusers,
                obj=obj,
            )
        return self.none()


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base user class.
    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = "%s" % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro02/base/views.py
from django.shortcuts import render
# from django.http import HttpResponse


def home(request):
    return render(request, 'base/home.html')

pypro02/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">

		<title>{% block title %}Python Pro{% endblock title %}</title>

		<meta name="description" content="{% block description %}Página do curso Python Pro{% endblock description %}">
		<meta name="author" content="Fabio Zanetti">

		<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}">
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="{% static 'css/style.css' %}" rel="stylesheet">
		<script src="{% static 'js/jquery.min.js' %}"></script>
<!--		<script src="{% static 'js/bootstrap.min.js' %}"></script>-->
		<script src="{% static 'js/bootstrap.bundle.min.js' %} "></script>
		<script src="{% static 'js/scripts.js' %}"></script>
	</head>
	<body>
		<nav class="navbar navbar-expand-lg bg-body-tertiary" data-bs-theme="dark">
			<div class="container-fluid">
				<a class="navbar-brand" href="{% url 'base:home' %}">Python Pro</a>
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
						aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse" id="navbarSupportedContent">
					<ul class="navbar-nav me-auto mb-2 mb-lg-0">
						<li class="nav-item dropdown">
							<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
							   aria-expanded="false">
								Módulos
							</a>
							<ul class="dropdown-menu">
								{% for modulo in MODULOS %}
								<li><a class="dropdown-item" href="{{ modulo.get_absolute_url }}">{{ modulo.titulo }}</a></li>
								<li><hr class="dropdown-divider"></li>
								{% endfor %}
							</ul>
						</li>
					</ul>
					{% if user.is_authenticated %}
						<ul class="navbar-nav mb-2 mb-lg-0">
							<li class="nav-item dropdown">
								<a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
								   aria-expanded="false">
									{{ user.first_name }}
								</a>
								<ul class="dropdown-menu">
									<li>
										<div class="dropdown-item">
											<form action="{% url 'logout' %}" method="POST">
												{% csrf_token %}
												<button class="btn btn-danger" type="submit">Sair</button>
											</form>
										</div>
									</li>
								</ul>
							</li>
						</ul>
					{% else %}
						<a class="btn btn-light" href="{% url 'login' %}">Entrar</a>
					{% endif %}
				</div>
			</div>
		</nav>

		{% block body %}{% endblock body %}

		{% include 'base/footer.html' with contato_email='ramalho@python.com.br' only %}

	</body>
</html>

pypro02/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-3 text-light">
			<div class="container">
				<div class="row">
					<div class="col">
						<h3>Entre em contato</h3>
						<address>
							+55 19 96321 1235
							<br/>
							<a class="text-light" href="mailto:{{ contato_email }}">{{ contato_email }}</a>
						</address>
					</div>
				</div>
			</div>
			<div class="rights">
				<div class="container pb-4">
					<div class="row">
						<div class="col">
							{% now 'Y' %} Todos direitos reservados.
						</div>
					</div>
				</div>
			</div>
		</footer>

pypro02/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}Python Pro - Home{% endblock title %}

{% block body %}
<div class="container">
			<div class="row">
				<div class="col-md-12">
					<div class="jumbotron bg-secondary-subtle rounded py-5 ps-4 my-2">
						<h2>
							Curso de Python com Luciano Ramalho
						</h2>
						<h4 class="pt-3">Matrículas abertas: R$1.000,00</h4>
						<!-- INICIO DO BOTAO PAGSEGURO -->
						<a href="https://pag.ae/7Z-YfP-NM/button" target="_blank" title="Pagar com PagSeguro">
							<img src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif" alt="Pague com PagSeguro - é rápido, grátis e seguro!" />
						</a><!-- FIM DO BOTAO PAGSEGURO -->

					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Mais detalhes sobre o instrutor
						</h5>
						<div class="card-body">
							<p class="card-text">
								<img class="img-thumbnail float-start me-3" src="{% static 'img/Luciano-Ramalho.jpeg' %}"
									 alt="Foto do Luciano Ramalho">
								Ramalho é sócio e professor na <a href="https://www.python.pro.br">Python Pro</a> e
								autor do Livro <a href="https://www.amazon.com/_/dp/1491946008?tag=oreilly20-20"
												  target="_blank">Fluent Python</a>. Foi diretor técnico do Brasil
								Online, primeiro portal da Abril S/A na Web. Liderou times para os portais IDG Now, BOL,
								UOL, AOL Brasil e outros, usando Python desde 1998. Como instrutor, atendeu clientes
								como Citibank, CPqD, Serpro, Presidência da República, Globo.com e Itaú. Palestrante em
								eventos internacionais como FISL, PyCon US e OSCON. Ajudou a criar a Associação Python
								Brasil e foi seu presidente. É membro da Python Software Foundation e fundador do Garoa
								Hacker Clube, o primeiro hackerspace do Brasil.
							</p>
						</div>
					</div>
				</div>
			</div>
		</div>
{% endblock body %}